# Generated by Django 4.2.3 on 2023-07-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatshopify', '0002_addfield_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddField',
        ),
    ]
