# Generated by Django 4.2.3 on 2023-08-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatshopify', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='assets/')),
            ],
        ),
    ]
