# Generated by Django 4.2.3 on 2023-08-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatshopify', '0005_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='description',
        ),
    ]
